### ISSUE TITLE
forceRootUrl called twice with wrong config name

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#105]
I think it should be calling `forceScheme` and `forceRootUrl`, but it is actually calling `forceRootUrl` twice

https://github.com/LCAS/pgr_system/blob/d13c4ea08203b18a6f891ca9d541624453dfcbba/app/Http/Middleware/RoutePrefixProxy.php#L18-L23

**Comment by pet1330** [comment]
I appreciate in our instance they reflect the same value, but it should still be changed :smiley:

**Comment by marc-hanheide** [comment]
Well and true
