### ISSUE TITLE
interruption time to be calculated from total duration

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#107]
At the moment the dates are calculated from the working days, but it should be changed to total days. Maybe @pet1330 could advise?

**Comment by pet1330** [comment]
Just revert this commit https://github.com/LCAS/pgr_system/commit/a2657ae035a1cd89db40d8d9546590936e2b6774 :)

**Comment by pet1330** [comment]
Specifically, change this function: https://github.com/LCAS/pgr_system/blob/0c846b2ab8e3682d457963c8860a8185aaee4468/resources/assets/js/app.js#L65-L79

**Comment by pet1330** [comment]
Closing this for now as 5e8b2ff56011fb29234e552df9265638b0ae0010 fixes it, however, it's probably worth noting that this change does not fix interruptions that have already been assigned. They will have to be corrected manually.

You can loop through the database and set the duration to be the difference between the start and end date, but this will override any durations that were deliberately changed by the user.

If you do decide to correct existing data this way, you will also need to call the recalculate due date for each student as well
