### ISSUE TITLE
Abilities Sometimes Reset

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#111]
Jane reported that when upgrading a staff member to an admin, they sometimes lose all of their abilities. However, this appears to be a bigger problem than that as you can find users who have been affected by doing the following:

```php
App\Models\Admin::whereDoesntHave('abilities')->get()
```

Currently, it appears to be affecting 653 users.

**Comment by marc-hanheide** [comment]
This currently returns one user. Does this mean in the process of updating to admin the entire abilities are lost?

**Comment by pet1330** [comment]
Yes, 1 admin, but if you do 653 users,
```php

App\Models\User::whereDoesntHave('abilities')->get()

```

**Comment by marc-hanheide** [comment]
Is it because they never logged in, maybe?

**Comment by pet1330** [comment]
quite possibly, it may be worth checking whether permissions are assigned when the user is created or when they log in
