### ISSUE TITLE
Updating milestone due date with a deleted type

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#112]
When updating a Milestone which has a deleted type, the edit form automatically changes the type to whatever is at the top of the dropdown list. It does this as the existing type value does not appear in the list. 

This requires the form and validation logic to be changed to allow the update to occur with a deleted MilestoneType. By not providing the value the server will update the remaining values i.e. just the due date in this case.

However, if the type is changed, then it must be validated and updated, as it currently is.

**Comment by marc-hanheide** [comment]
I'm not sure that's actually what is intended here. If a milestone-type is deleted we should probably recurse-delete all milestones... I'm still not sure what the users actually expected when deleting the type.

**Comment by pet1330** [comment]
You do not want to delete all milestones with the old type. You only want to prevent new milestones being created with the deleted type. For example, if the regulations say I have to complete a `GS4`, but then the regulations change after I have been assigned to them, you do not want to delete the milestone I have already submitted (as I will still be required to complete the `GS4`). You also do not want to change the milestone type for the existing milestone just because it is being pushed back a bit (by changing the due date).

Therefore, any milestone that has been created with a particular milestone type need to remain in place and still be editable after the milestone type has been deleted. This will allow milestones to be pushed back (i.e. their due dates changed) even after the milestone type has been deleted.

**Comment by marc-hanheide** [comment]
We need to talk to the admin team again to fully understand the different use cases. My suspicion is that MilestoneTypes rather should never be deleted (through the interface). The shall be removed from timelines, yes, but normally not be removed. Removing them could have different use cases in mind:
* It was a mistake that type was created and it should be removed, including all instances of that type on students' milestones
* Regulations have changed and the type is no longer required, in which case the instances must remain and remain amendable. 

My proposal:
* instances of milestones should in fact never be amendable with regard to the MilestoneType (the dates should be). If indeed another type is needed, a new one has to be instantiated, and the old one removed. This is more in line with actual use cases and solves this issue #112
* We _may_ remove the deletion option for MilestoneType from the interface, but for now this can be optional.

**Comment by marc-hanheide** [comment]
project discontinued
