### ISSUE TITLE
ErrorException: file_put_contents(/var/www/html/pgr/storage/framework/views/abff0fe95831ff134ee10d75c6ca3f372a00e...

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#19]
https://sentry.io/university-of-lincoln/pgr-system/issues/552153808/

```
ErrorException: file_put_contents(/var/www/html/pgr/storage/framework/views/abff0fe95831ff134ee10d75c6ca3f372a00e104.php): failed to open stream: Permission denied
  File "artisan", line 35
    new Symfony\Component\Console\Output\ConsoleOutput
...
(41 additional frame(s) were not displayed)
```

**Comment by marc-hanheide** [comment]
odd thing is that it should use redis as cache driver...

**Comment by marc-hanheide** [comment]
This was likely the result of an `artisan` command executed as root. We must make sure that, if running artisan as `root` and not as `www-data` to reset the owner of cache files to `www-data`, e.g.` using `sudo chown -R www-data:www-data /srv/pgr/storage/framework/` on the host

**Comment by pet1330** [comment]
Ah, that was my mistake. Sorry! We should also add the following to the docker deploy script:
```bash
    php artisan clear-compiled
    php artisan cache:clear
    php artisan route:clear
    php artisan view:clear
    php artisan config:cache
    php artisan routes:cache
    composer dump-autoload
```
