### ISSUE TITLE
reminders need to be send also to supervisor

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#21]
currently they only go to student.

**Comment by marc-hanheide** [comment]
And, by request of _some_ admins, also to the respective school admin 🙄

**Comment by pet1330** [comment]
It may also be worth saving a record of notifications to the database as currently, we do not monitor which notifications are sent

**Comment by marc-hanheide** [comment]
> It may also be worth saving a record of notifications to the database as currently, we do not monitor which notifications are sent

I have set up [maildev](https://danfarrelly.nyc/MailDev/) as part of the docker deployment, and all system-sent emails are relayed through it, so we can see them there. Doesn't archive them for longer, but is good enough for now.
