### ISSUE TITLE
both reminder emails sent on due date

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#22]
Also the starting reminder is sent again at the due date:

![image](https://user-images.githubusercontent.com/1153084/40098673-03230406-58dd-11e8-8e49-cbc35f98a4bf.png)

Also, the wording can be improved (and supervisors also notified, see #21

**Comment by pet1330** [comment]
The upcoming reminder should *_in theory_* be sent 7 days before the due date: 
![image](https://user-images.githubusercontent.com/4920245/40116761-90b396f8-590c-11e8-8b2f-58753dc9612d.png)

**Comment by marc-hanheide** [comment]
The upcoming reminder was sent 7 days ago, I think, the problem is it was sent again at the due date (15/5/18)

**Comment by marc-hanheide** [comment]
while investigating this, I came across this [line](https://github.com/LCAS/pgr_system/blob/dockerised/app/Models/Milestone.php#L204)

```
    public function startsToday()
    {
        return $this->start_date->isToday();
    }
```

And I can't figure out where the `start_date` is actually coming from. Sorry, @pet1330, can you enlighten me?

**Comment by pet1330** [comment]
In Laravel, you can create getter and setter functions by naming them `getAttributeNameAttribute()`. In this case, the function is called `getStartDateAttribute` and allows you to access it as a property rather than a function.

https://github.com/LCAS/pgr_system/blob/8213be758fb602d7f03b9f972bd868079c78e2f0/app/Models/Milestone.php#L193-L197

**Comment by marc-hanheide** [comment]
How intuitive ;-)

**Comment by marc-hanheide** [comment]
and indeed it seems no early upcoming reminder is sent, so the upcoming reminder is sent at the due date and *not* at `due_date-duration`.

**Comment by marc-hanheide** [comment]
Have you ever checked if https://github.com/LCAS/pgr_system/issues/22#L196 works as expected?

**Comment by pet1330** [comment]
I only check that they were being sent, I never explicitly checked that they were being sent at the correct time.

**Comment by marc-hanheide** [comment]
OK, problem is clear:

here an example from the production database:

```
       App\Models\Milestone {#3272
         id: 6634,
         name: null,
         duration: 0,
         duration_unit: "Months",
         submitted_date: null,
         due_date: "2018-11-01 00:00:00",
         non_interuptive_date: "2018-11-01 00:00:00",
         student_record_id: 160,
         milestone_type_id: 8,
         created_by: 1,
         deleted_at: null,
         created_at: "2018-03-06 16:02:49",
         updated_at: "2018-03-06 16:02:49",
         type: App\Models\MilestoneType {#3330
           id: 8,
           name: "PGR Thesis Submission Form",
           student_makable: 1,
           duration: 7,
           deleted_at: null,
           created_at: "2017-10-05 14:47:32",
           updated_at: "2017-10-05 14:47:32",
         },
         approvals: Illuminate\Database\Eloquent\Collection {#3487
           all: [],
         },
       },
```
duration here is `0` and not `null`, so https://github.com/LCAS/pgr_system/blob/master/app/Models/Milestone.php#L84 returns '0' and not the duration of the type itself. Hence, the notification query in https://github.com/LCAS/pgr_system/blob/master/routes/console.php#L14-L22 checks that the type's duration is not null, but then uses the `start_date` property of the milestone itself, which in this case returns indeed the `due_date-duration`

@pet1330 I see two options:

1. change https://github.com/LCAS/pgr_system/blob/master/app/Models/Milestone.php#L84 to only ever report the `MilestoneType::duration`, and remove the milestone specific duration. I don't think we ever used the `Milestone::duration` really (it is seeded in the database but not filled properly in the production system I believe)
1. Indeed copy the `MilestoneType::duration` over into a milestone when it is created, but I think that is even not what we want, because we may want to change the duration permitted for a student to work on a milestone after the MS has been created. So, I think option 1 is preferable.

Opinions, @pet1330

**Comment by pet1330** [comment]
That's great, well spotted! I would change the `??` to `?:` in https://github.com/LCAS/pgr_system/blob/master/app/Models/Milestone.php#L84

As this is what it should have been in the first place, but also it will allow individual milestone extentions to be added if need be.

![screenshot_20181101-194910_dcoder](https://user-images.githubusercontent.com/4920245/47875795-5e229300-de0f-11e8-9868-71f760774903.jpg)
