### ISSUE TITLE
auto-compute length of interruption from dates

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#23]

**Comment by pet1330** [comment]
I tried to do this a while ago but it is difficult to do as different types of interruptions include different days. For example, interruption of studies includes all days, but holidays only include working days, etc. Plus, to make it accurate enough to worth having, you would also have to keep a list of the University holidays (i.e. term dates and bank holidays).

In the end, I decided against it, as if you just autocomplete **all** days, users will just assume the system has worked it out correctly and will not check it, leading to errors

**Comment by marc-hanheide** [comment]
I'll ask the admins what they deem a suitable solution. At the moment it leads to even more mistakes as they also don't know what to put in.

**Comment by marc-hanheide** [comment]
It seems, also registry make it up as the go along. @pet1330 where did you get you information from that sometime it's working days only, sometimes all days? I can't find this anywhere.

I assumed it is always working days. I didn't think holidays push anything at all, do they?

My understanding is that to calculate the new max reg date, they use this: https://www.timeanddate.com/date/workdays.html

As their API is costly, I propose to simply use the freely available gov.uk API: https://www.gov.uk/bank-holidays.json, and calculate the working days in javascript and prepopulate the days field with the corresponding working days, _if_ the absence if of type interrupting. Does that make sense?

**Comment by marc-hanheide** [comment]
preserving my jsfiddle for this here: 

```
function get_bank_holidays() {
  $.getJSON('https://www.gov.uk/bank-holidays.json', function(data) {
    banner.addClass("alt");
    console.log(data);
    var event_lst = data['england-and-wales'].events;
		var holidays = [];
    for (var d in event_lst) {
      var bhd = event_lst[d].date.split('-');
      var dt = new Date(bhd[0], bhd[1], bhd[2]);
      holidays.push(dt);
      console.log(bhd);
    }
    console.log(holidays);
  });
}

```

to be used later to complete this.

**Comment by pet1330** [comment]
This is what I was told by the school office, although, it may be worth asking HR what the official policy is?
