### ISSUE TITLE
soft-delete / set closed for students

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#32]
We need a way to clean up when students are "closed". There are different ways to achieve that. By default "closed" records should not be visible in any views. Maybe a global flag under "settings" can allow admin people to switch on "closed" students. I think it might be best to have a dedicated field `closed` (indexed) in the student record, and amend the queries to take this onto account. Ideas @pet1330

**Comment by pet1330** [comment]
This is currently implemented as [soft delete](https://laravel.com/docs/5.6/eloquent#soft-deleting). When you create a new student record, their old one is soft deleted.
https://github.com/LCAS/pgr_system/blob/f2d499ba5822b82aae1cd62d1c359909c0f5c57f/app/Http/Controllers/StudentRecordController.php#L70

You can simply add a button to the dashboard which calls a `destroy` function on the [StudentRecordController](https://github.com/LCAS/pgr_system/blob/master/app/Http/Controllers/StudentRecordController.php) which simply calls
```php
    $student->records->each->delete() // (to delete all records)
```
or

```
    $record->delete() // (for a specific record)
```

**Comment by marc-hanheide** [comment]
but then we can't see the student again, if we want, right? What would be the restore procedure?

**Comment by pet1330** [comment]
```
    $student->records()->withTrashed()->first()->restore()
```

**Comment by pet1330** [comment]
This is also how the Colleges, Schools, Funding Types, Absence Types, Programmes, Student Statuses and Enrolment Statuses work. 

You can delete them, then they are added to a "Deleted" list at the bottom of the page which can be easily restored

**Comment by pet1330** [comment]
See pet1330/pgr_system#60
