### ISSUE TITLE
Student details

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#33]
Submitter: Lorna Lancaster
Email: llancaster@lincoln.ac.uk
As PGR lead for the school I was expecting to see all students from the school to determine if the students are completing forms etc.  Also I am second supervisor to some other students that are not listed in my dashboard

**Comment by marc-hanheide** [comment]
Apparently the user can't see any students in the user menu (won't open), maybe browser related (IE/edge??).

**Comment by marc-hanheide** [comment]
Ever tested on MS browsers @pet1330 ?

**Comment by marc-hanheide** [comment]
it worked in Chrome for her...

**Comment by marc-hanheide** [comment]
internet explorer was the problem (still default in many colleagues' systems), not even edge.

**Comment by pet1330** [comment]
It was tested on IE11, Edge, Firefox and Chrome. It all seemed to work on the remote desktop and the corporate desktop in the Admin office. Do you have the JS error message?

**Comment by marc-hanheide** [comment]
Obviously not, no server side error was there. Maybe JavaScript wasn't even enabled who know.

**Comment by pet1330** [comment]
I've just gone back and checked, as far as I can tell, everything is working IE9+. If they are using IE5, IE7 (default on the cloud desktop for some reason) or IE 8, the system will not work. I will speak to ICT to find out why these versions still exist on the cloud desktop.
![screenshot from 2018-07-19 15 17 23](https://user-images.githubusercontent.com/4920245/42948506-84c9724e-8b67-11e8-85ba-6867645307cb.png)
![screenshot from 2018-07-19 15 21 30](https://user-images.githubusercontent.com/4920245/42948507-84e7f584-8b67-11e8-8a30-a8be3fc4242c.png)

**Comment by marc-hanheide** [comment]
That's a good alternative, thanks for looking into this.

**Comment by marc-hanheide** [comment]
closed by https://github.com/pet1330/pgr_system/pull/61
