### ISSUE TITLE
interruption doesn't change due date

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#49]
I have tried everything, and an interruption doesn't seem to change the due date of any milestones, even it is set to be interruptive.

My understanding is that it should do it here:
https://github.com/LCAS/pgr_system/blob/master/app/Models/Milestone.php#L287-L292

```
    public function recalculateDueDate()
    {
        return $this->update(['due_date' => $this->non_interuptive_date
            ->copy()->addDays($this->student->student
                ->interuptionPeriodSoFar()), ]);
    }
```

which then calls https://github.com/LCAS/pgr_system/blob/master/app/Models/Student.php#L95-L102
```
    public function interuptionPeriodSoFar(Carbon $at_point = null, $include_current = true)
    {
        return $this->absences->filter(function (Absence $ab) {
            return (bool) $ab->type->interuption;
        })->filter(function (Absence $ab) use ($at_point, $include_current) {
            return $ab->isPast($at_point) || $ab->isCurrent($at_point) && $include_current;
        })->sum('duration');
    }
```

My understanding is, that this will filter all absences that are in the past _TODAY_ (as the argument is zero) and will calculate their sum. But when we enter interruptions they will in most cases be in the future, right? Should this be called with the current `due_date` of the respective milestone, @pet1330 ?

**Comment by pet1330** [comment]
In that case, this should be called with the interruption start date as the first argument.

@marc-hanheide Can you write some tests to show this working, similar tests have been written as demonstrations in the #55

**Comment by marc-hanheide** [comment]
This seems also flawed in other places, such as

https://github.com/LCAS/pgr_system/blob/d13c4ea08203b18a6f891ca9d541624453dfcbba/app/Http/Controllers/MilestoneController.php#L307-L312

**Comment by marc-hanheide** [comment]
I need some hlpe with this, I notice... @pet1330

**Comment by pet1330** [comment]
Okay, I've written some tests and have found the issue (plus a few issues with some of my other tests), I'll make a pull request tomorrow to fix it.
