### ISSUE TITLE
Documentation links in app

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#72]
We should include links to PGR regulations, forms and to the documentation in respective pages. Best to include html fragments in environment that are displayed in milestone page and dashboards

**Comment by pet1330** [comment]
I was originally going to add the templates (word documents) on the milestone type so that it shows up on the student's dashboard, but it meant that someone would have to keep it up to date when they change. External links wouldn't be great as they require the user to be logged into the portal

**Comment by marc-hanheide** [comment]
I was thinking to not refer to individual templates but rather have one link (configured in `.env`) on the milestone page. Or rather, have the option to put any html fragment on some key pages.

**Comment by marc-hanheide** [comment]
I have already added a menu item "help" linking to the GitHub.io page which I expanded for actual general documentation of the application, not UoL specific stuff.
