### ISSUE TITLE
awaiting amendments list not complete

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#77]
Submitter: Marc Hanheide
Email: marc@hanheide.net
it says in the dashboard and also at the bottom of the list view that there are 5, but it lists only 2! https://lcas.lincoln.ac.uk/pgr/student/amendments

**Comment by marc-hanheide** [comment]
@pet1330 this is indeed a problem, there are also data-table errors popping up for these views

**Comment by pet1330** [comment]
I think this issue may be related to #79

**Comment by marc-hanheide** [comment]
Looking at https://lcas.lincoln.ac.uk/pgr/student/amendments it doesn't seem solved, even in 0.0.6 (currently deployed):
![image](https://user-images.githubusercontent.com/1153084/48450667-008f2e80-e79f-11e8-97bf-4d8175702fc4.png)

2 shown, but it says 5 shown.

**Comment by marc-hanheide** [comment]
Also in https://lcas.lincoln.ac.uk/pgr/student/upcoming the problem appears to be the same. Says "Showing 1 to 76 of 76 entries", but Excel export results in 61 entries.

**Comment by marc-hanheide** [comment]
Or is it a data tables problem. I can confirm that indeed the number 5 looks more likely correct, than just the 2 entries we see. In particular one student already has two amendments to make...

**Comment by pet1330** [comment]
This may also be connected to #84, but I will leave it open we can confirm it

**Comment by marc-hanheide** [comment]
I think this problem may be a different one. But I agree it has something to do with the actual data, not the implementation. It works all 100% correct on the test system. So, somehow some entries must be messed up in a way that causes this bug.

**Comment by pet1330** [comment]
@marc-hanheide Now that #84  has been resolved, can you confirm that this issue still exists?

**Comment by marc-hanheide** [comment]
It seems that in the `Milestone` the record is still accessed as `student`, right? So not really sure changing this to record does the right thing, do you?
 
https://github.com/LCAS/pgr_system/blob/6a11dd77f1e4c18a99fc56ff5e7f061c9e9b1143/app/Models/Milestone.php#L87-L90

**Comment by pet1330** [comment]
Yeah, I had a play with this last night and that does not seem to be the problem.

Although those references to student, (along with the function) should still be changed to record as its more representive of what the relationship is.

**Comment by marc-hanheide** [comment]
> Although those references to student, (along with the function) should still be changed to record as its more representive of what the relationship is.

Sure, but that is a cosmetic change, not fixing this bug...
