### ISSUE TITLE
name change for students

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#78]
particularly relevant when they get married for instance...

**Comment by marc-hanheide** [comment]
Shouldn't be needed as name is updated automatically when student logs in, right @pet1330 ?

**Comment by pet1330** [comment]
Yeah, the name is fetched from the active directory when they next log in

**Comment by marc-hanheide** [comment]
Just a follow up on this. For staff and admins the situation is different I presume? Their uni ID is composed of their surname and I have seen staff having their email address changed. So in that case they would also get a new account in our system, right? Not a big deal, but possibly a problem to bear in mind.

**Comment by pet1330** [comment]
In theory, it should up date as well, as even if their email changes their account ID from the Active Directory should be the same. (so long as ICT updates their account email address and name, instead of just closing it and reopening a new one)
