### ISSUE TITLE
Yajra\DataTables\Exceptions\Exception: Trying to get property of non-object

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#79]
https://sentry.io/university-of-lincoln/pgr-system/issues/762283747/

```
ErrorException: Trying to get property of non-object
  File "app/Http/Controllers/MilestoneController.php", line 160, in handleError
    return $ms->student->school->name;
  File "app/Http/Controllers/MilestoneController.php", line 160, in App\Http\Controllers\{closure}
    return $ms->student->school->name;
  File "app/Http/Controllers/MilestoneController.php", line 89, in upcoming
    return $this->data(Milestone::select('milestones.*')->upcoming())->make(true);
  File "app/Http/Middleware/SamlAuth.php", line 26, in handle
    return $next($request);
  File "app/Http/Middleware/DevUser.php", line 25, in handle
    return $next($request);
...
(64 additional frame(s) were not displayed)

Yajra\DataTables\Exceptions\Exception: Trying to get property of non-object
  File "app/Http/Controllers/MilestoneController.php", line 89, in upcoming
    return $this->data(Milestone::select('milestones.*')->upcoming())->make(true);
  File "app/Http/Middleware/SamlAuth.php", line 26, in handle
    return $next($request);
  File "app/Http/Middleware/DevUser.php", line 25, in handle
    return $next($request);
  File "app/Http/Middleware/RoutePrefixProxy.php", line 25, in handle
    return $next($request);
  File "public/index.php", line 52
    $request = Illuminate\Http\Request::capture()
...
(58 additional frame(s) were not displayed)
```

**Comment by pet1330** [comment]
I'm not sure what is causing this, but it only started occurring on the 13th November 2018 around 3pm. What did you change around that time? (I cannot replicate it locally)

**Comment by pet1330** [comment]
After a bit more investigating:

It is an issue in the database, not the datatables, run this in thinker on the production server to get a list of Milestones which are erroring:

```
\App\Models\Milestone::chunk(50, function($mscollection) {
    $mscollection->each(function($ms) {
        if (! isset($ms->student)) {
            echo $ms->id;
            echo "\n";
        }
    });
});
```

It should produce the following Milestone IDs which have a null StudentRecord:

```
[3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3356, 5869, 5870, 5872, 5873]
```

This is a list of all the missing StudentRecords (not all of them have milestones):
```
[8, 9, 10, 11, 12, 21, 50, 65, 90, 95, 105, 112, 134, 140, 141, 212, 221, 252, 255, 257]

```

**Comment by pet1330** [comment]
I think it may have something to do with the archived records...

**Comment by pet1330** [comment]
Okay, I've fixed it. 

Previously, when records were archived the milestones that were associated with the record didn't get archived. 

This issue was then fixed so all the newer records that were archived did have their associated milestones archived as well. But because this wasn't retrospective, this meant that there was a load of milestones in the system that weren't associated with an active record.

To solve it, I have unarchived and then rearchived all of the records so that they are run through the additional process and have all of their milestones archived as well.

**Comment by marc-hanheide** [comment]
You are a star! Would have taken me ages to find that.

**Comment by pet1330** [comment]
On this same note, it might be worth going through all of the milestones and calling the new recalculate due date function:

```php

\App\Models\Milestone::chunk(50, function($mscollection) {
    $mscollection->each(function($ms) {
            $ms->recalculateDueDate();
        }
    });
});

**Comment by marc-hanheide** [comment]
rather

```
\App\Models\Milestone::chunk(50, function($mscollection) {
    $mscollection->each(function($ms) {
            $ms->recalculateDueDate();
        }
    );
});
```

but done.
