### ISSUE TITLE
admin-absence-type-table - Requested unknown parameter 'currentabsence_count' 

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#81]
![image](https://user-images.githubusercontent.com/1153084/48450561-9ecec480-e79e-11e8-9fbd-352c496a0da3.png)

https://lcas.lincoln.ac.uk/pgr/settings/absence-type

```
DataTables warning: table id=admin-absence-type-table - Requested unknown parameter 'currentabsence_count' for row 0. For more information about this error, please see http://datatables.net/tn/4
```

results in `current` column being empty. @pet1330 any immediate idea before I investigate further

**Comment by pet1330** [comment]
It's probably something to do with [this line](https://github.com/LCAS/pgr_system/blob/9cdc19bdce8eb2e048ca910e7bd4c5597f04a1b2/app/Http/Controllers/AbsenceTypeController.php#L25) 

But I can't see anything obviously wrong with it
