### ISSUE TITLE
Swift_TransportException: Expected response code 354 but got code "503", with message "503 Error: need RCPT command

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#82]
https://sentry.io/university-of-lincoln/pgr-system/issues/758668471/

```
Swift_TransportException: Expected response code 354 but got code "503", with message "503 Error: need RCPT command
"
  File "artisan", line 35
    new Symfony\Component\Console\Output\ConsoleOutput
...
(40 additional frame(s) were not displayed)
```

**Comment by marc-hanheide** [comment]
Any idea what this means?

**Comment by pet1330** [comment]
No idea. It's to do with the mail notifications not being sent. I think this is an external issue rather than an issue with the application itself, but I'm not sure what is causing it

**Comment by pet1330** [comment]
This has not occurred since the 16th November, so I'm going to assume it is no longer an issue
