### ISSUE TITLE
Milestone Edit incorrect

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#84]
Submitter: Pete

Rather than updating a `MilestoneType` name, they are being deleted, and new ones are being created.

Correctly, this does not update past milestones which still point to the old (archived)  milestone type:

Milestone example: `P2KwQbj6z8e`

I think this is a training error rather than a system error. I cannot think of a way of stopping this from happening. The only thing that might be useful would be to add the ability to merge two `MilestoneType`s to make it easier to resolve after the fact

**Comment by marc-hanheide** [comment]
@pet1330 can you explain this a bit more?

I have tried in the test system to rename a milestone, (in the milestone types) and it worked fine. What do you things the admins did and that is a training error?

**Comment by pet1330** [comment]
Look at the production database, `TDNAA` has been archived and `RDNAA` has been newly created. However, they wanted this change to be retrospective and apply to ALL milestones, new and old. In which case `TDNAA` should have been renamed, rather than archived and a new `MilestoneType` created

**Comment by pet1330** [comment]
This is not a software issue, but a user issue. It has been amended on the production database
