### ISSUE TITLE
interruption

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#86]
Submitter: Jane Chapman
Email: jchapman@lincoln.ac.uk
Had to work out dates for the above for Eowyn Butler.  He is interrupting from 1/11/2018 and returning 2/12/2019 and whilst we selected relevant dates we had to do manually - it didnt work out the days for us

**Comment by marc-hanheide** [comment]
sometimes, the system needs to retrieve the official holidays from the government system and cache it. I have noticed that sometimes this takes a little longer. It helps to click on dates again in this case. The result is then cached, and subsequent clicks update the number immediately.

**Comment by pet1330** [comment]
A simple fix would be to trigger the event twice for every click.

**Comment by marc-hanheide** [comment]
yeah, but if you just do it immediately, there now benefit, is there. And if you do it after a while, it may lead to conflicts with quick actual events.
