### ISSUE TITLE
Student Names

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#88]
Submitter: Jane Chapman
Email: jchapman@lincoln.ac.uk
Hi, 2 maths students names have been input incorrectly.  Are you able to amend or if can we just archive those files and then add the students again to the database - just want to make sure this wont cause any issues.

**Comment by pet1330** [comment]
The students will be renamed when they login, there is currently no way to rename students manually through the web interface as the values will simply get overwritten when the student next logged in
