### ISSUE TITLE
Supervisor milestone permission assignment

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#98]
This line is likely to be the causes of the permission issue that was reported. 

It should be `$record->supervisors->`.... rather than `$student->supervisors->`... As supervisors are linked with the student record not the student directly 

https://github.com/LCAS/pgr_system/blob/cbe91b224c1a0ebaf14c1e3c9fdba86947dd155e/app/Http/Controllers/MilestoneController.php#L233

(You may just want to check that this is the case as I have not had time to actually run the code and check)

**Comment by marc-hanheide** [comment]
You mean the error when milestones are created, right? Or which permission issue are you referring to?

**Comment by pet1330** [comment]
Yes, when new milestones are created the student is assigned permissions to upload and view, but the supervisor is not assigned view permissions. There used to be a property on the student object that would get the supervisors from their first record, but that was recently removed. As such, adding milestones now will error
